appName = "iHR"
env = "local"
jwtSecret = ""
[database]
host = "db"
port = 3306
username = ""
password = ""
dbname = ""
[redis]
host = "redis"
port = 6379
[oauth.google]
clientID = ""
clientSecret = ""
